icon_dir = "./GUI/icons/"

merge_icon = icon_dir + "merge.png"
division_icon = icon_dir + "merge.png"
pdf_to_png_icon = icon_dir + "merge.png"
png_to_pdf_icon = icon_dir + "merge.png"
add_icon = icon_dir + "add.png"
open_icon = icon_dir + "open.png"
remove_icon = icon_dir + "remove.png"
rename_icon = icon_dir + "rename.png"
save_icon = icon_dir + "save.png"
save_as_icon = icon_dir + "saveas.png"
search_icon = icon_dir + "search_dialog.png"
help_icon = icon_dir + "help.png"
quit_icon = icon_dir + "quit.png"
